<?php

namespace Books\Chat\Components;

use Cms\Classes\ComponentBase;

/**
 * Messenger Component
 *
 * @link https://docs.octobercms.com/3.x/extend/cms-components.html
 */
class Messenger extends ComponentBase
{
    public function componentDetails()
    {
        return [
            'name' => 'Messenger Component',
            'description' => 'No description provided yet...',
        ];
    }

    /**
     * @link https://docs.octobercms.com/3.x/element/inspector-types.html
     */
    public function defineProperties()
    {
        return [];
    }

    public function onRun()
    {
        parent::onRun(); // TODO: Change the autogenerated stub
        $this->addJs(themes_path('/demo/chat/assets/js/**.js'));
    }
}
