<?php

namespace Books\Notifications\Classes\Actions;

class TestAction extends BookBaseAction
{
    public function triggerAction($params)
    {
        parent::triggerAction($params); // TODO: Change the autogenerated stub
    }
}
