<?php namespace Books\Book\Controllers;

use BackendMenu;
use Backend\Classes\Controller;
use Books\Book\FormWidgets\SystemMessagePreview;

/**
 * System Message Backend Controller
 *
 * @link https://docs.octobercms.com/3.x/extend/system/controllers.html
 */
class SystemMessage extends Controller
{
    public $implement = [
        \Backend\Behaviors\FormController::class,
        \Backend\Behaviors\ListController::class,
    ];

    /**
     * @var string formConfig file
     */
    public $formConfig = 'config_form.yaml';

    /**
     * @var string listConfig file
     */
    public $listConfig = 'config_list.yaml';

    /**
     * @var array required permissions
     */
    public $requiredPermissions = ['books.book.systemmessage'];

    /**
     * __construct the controller
     */
    public function __construct()
    {
        parent::__construct();

        BackendMenu::setContext('Books.Book', 'book', 'systemmessage');
    }

    public function listExtendQuery($query)
    {
        $query->orderBy('created_at', 'desc');
    }

    public function beforeDisplay()
    {
        parent::beforeDisplay(); // TODO: Change the autogenerated stub

    }

}
