<?php namespace Books\Book\Components;

use Books\Book\Models\Book;
use Flash;
use Request;
use Redirect;
use Exception;
use Cms\Classes\ComponentBase;
use RainLab\User\Facades\Auth;
use Books\Book\Models\BookStatus;

/**
 * ECommerceBooker Component
 *
 * @link https://docs.octobercms.com/3.x/extend/cms-components.html
 */
class ECommerceBooker extends ComponentBase
{

    protected int $book_id;
    protected Book $book;

    /**
     * componentDetails
     */
    public function componentDetails()
    {
        return [
            'name' => 'ECommerceBooker Component',
            'description' => 'No description provided yet...'
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->book = Auth::getUser()?->books()->find($this->param('book_id'));
    }

    public function onRun()
    {
        $this->page['bookStatusCases'] = BookStatus::publicCases();
    }

    public function onUpdateEcommerce()
    {
        try {
            $this->book->update(post());
            $this->book->setFreeParts();

            return Redirect::to('/about-book/' . $this->book->id);

        } catch (Exception $ex) {
            if (Request::ajax()) throw $ex;
            else Flash::error($ex->getMessage());
        }
    }

    /**
     * defineProperties for the component
     *
     * @link https://docs.octobercms.com/3.x/element/inspector-types.html
     */
    public function defineProperties()
    {
        return [];
    }
}
