version: '3'
services:
    nginx:
        image: nginx:1.21.1-alpine
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
            - '${WEBSOCKETS_LISTEN_PORT:-6002}:${WEBSOCKETS_LISTEN_PORT:-6002}'
        volumes:
            - ./docker/nginx/domain.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/snippets:/etc/nginx/snippets/:rw
            - ./docker/nginx/templates:/etc/nginx/templates/:ro
            - ./:/var/www/html
        environment:
            NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/snippets
        networks:
            - sail
        depends_on:
            - site.loc
    site.loc:
        restart: unless-stopped
        build:
            context: docker/php/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${APP_DEBUG:-false}'
        image: books-sail-8.1/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            COMPOSE_INTERACTIVE_NO_CLI: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    schedule:
        restart: unless-stopped
        image: books-sail-8.1/app
        environment:
            CONTAINER_ROLE: scheduler
            COMPOSE_INTERACTIVE_NO_CLI: 1
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - site.loc
    queue:
        restart: unless-stopped
        image: books-sail-8.1/app
        environment:
            CONTAINER_ROLE: queue
            COMPOSE_INTERACTIVE_NO_CLI: 1
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - site.loc
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        volumes:
            - './docker/soketi/soketi.json:/opt/config.json'
        command: [ "node", "/app/bin/server.js", "start", "--config=/opt/config.json" ]
        environment:
            SOKETI_DEBUG: '1'
            SOKETI_METRICS_SERVER_PORT: '9601'
            COMPOSE_INTERACTIVE_NO_CLI: 1
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        depends_on:
            - site.loc
        networks:
            - sail
    mysql:
        image: 'mariadb:10.5'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local
