version: '3'
services:
    nginx:
        image: nginx:1.21.1-alpine
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./docker/nginx/domain.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/snippets:/etc/nginx/snippets/:ro
            - ./:/var/www/html
        networks:
            - sail
        depends_on:
            - site.loc
    site.loc:
        restart: unless-stopped
        build:
            context: docker/php/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${APP_DEBUG:-false}'
        image: sail-8.1/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            COMPOSE_INTERACTIVE_NO_CLI: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - root
    schedule:
        restart: unless-stopped
        image: sail-8.1/app
        environment:
            CONTAINER_ROLE: scheduler
            COMPOSE_INTERACTIVE_NO_CLI: 1
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - root
        depends_on:
            - site.loc
    queue:
        restart: unless-stopped
        image: sail-8.1/app
        environment:
            CONTAINER_ROLE: queue
            COMPOSE_INTERACTIVE_NO_CLI: 1
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - root
        depends_on:
            - site.loc
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
networks:
    sail:
        driver: bridge
    root:
        external:
            name: "root_default"
volumes:
    sailredis:
        driver: local
