version: '3'
services:
    nginx:
        image: nginx:1.21.1-alpine
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
            - '${WEBSOCKETS_LISTEN_PORT:-6002}:${WEBSOCKETS_LISTEN_PORT:-6002}'
        volumes:
            - ./docker/nginx/domain.pomon.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/nginx/snippets:/etc/nginx/snippets/:rw
            - ./docker/nginx/templates:/etc/nginx/templates/:ro
            - /etc/letsencrypt/live/:/etc/letsencrypt/live/:ro
            - ./:/var/www/html
        environment:
            NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/snippets
        networks:
            - sail
        depends_on:
            - site.loc
            - soketi
    site.loc:
        restart: unless-stopped
        build:
            context: docker/php/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${APP_DEBUG:-false}'
        image: sail-8.1/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            COMPOSE_INTERACTIVE_NO_CLI: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - root
    schedule:
        restart: unless-stopped
        image: sail-8.1/app
        environment:
            CONTAINER_ROLE: scheduler
            COMPOSE_INTERACTIVE_NO_CLI: 1
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - root
        depends_on:
            - site.loc
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        volumes:
            - './docker/soketi/soketi-dev.json:/opt/config.json'
        command: [ "node", "/app/bin/server.js", "start", "--config=/opt/config.json" ]
        environment:
            SOKETI_DEBUG: '1'
            SOKETI_METRICS_SERVER_PORT: '9601'
            COMPOSE_INTERACTIVE_NO_CLI: 1
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        depends_on:
            - site.loc
        networks:
            - sail
            - root
    queue:
        restart: unless-stopped
        image: sail-8.1/app
        environment:
            CONTAINER_ROLE: queue
            COMPOSE_INTERACTIVE_NO_CLI: 1
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - root
        depends_on:
            - site.loc
networks:
    sail:
        driver: bridge
    root:
        external:
            name: "root_default"
