<?php

namespace App\middleware;

use Closure;
use Illuminate\Http\Request;
use RainLab\User\Facades\Auth;

class SetMessengerProvider extends \RTippin\Messenger\Http\Middleware\SetMessengerProvider
{
    public function handle(Request $request, Closure $next, $required = null)
    {
        return parent::handle($request, $next, $required = 'required'); // TODO: Change the autogenerated stub
    }

    protected function setProvider(Request $request): void
    {
        if ($profile = Auth::getUser()?->profile) {
            $this->messenger->setProvider($profile);
        }
    }
}
